// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace STAMP
{
    internal sealed partial class Vsix
    {
        public const string Id = "STAMP.7d8092a4-6950-4877-a6c6-2a2d1f1e14aa";
        public const string Name = "STAMP";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Lukáš Macek";
        public const string Tags = "";
    }
}
